# -*- mode: ruby -*-
# vi: set ft=ruby :

# This guide is optimized for Vagrant 1.7 and above.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|

#######################################
### WPS Servers  ######################
#######################################

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false
  config.ssh.private_key_path = '~/.vagrant.d/insecure_private_key'

  config.vm.define "slurm" do |slurm|
    # slurm.vm.box = "bento/ubuntu-18.04"
    # slurm.vm.box = "bento/ubuntu-16.04"
    slurm.vm.box = "bento/debian-9"
    # slurm.vm.box = "bento/centos-7"
    # slurm.vm.box = "bento/centos-6"
    # slurm.vm.box = "bento/fedora-27"
    slurm.vm.hostname = "slurm.local"
    slurm.vm.network "private_network", ip: "192.168.128.100"
    slurm.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'playbook.yml'
      ansible.verbose = "v"
      ansible.host_key_checking = false
    end
  end
end
