---
- name: Clone project code.
  git:
    repo: "{{ project_repo }}"
    dest: "{{ project_location }}"
    update: yes
  tags:
    git

- name: Create Conda environment from project environment file.
  command: "{{ conda_root }}/{{ conda_folder_name }}/bin/conda env update"
  args:
    chdir: "{{ project_location }}"
  tags:
    conda

- name: Create folders used by WPS and set owner
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "{{ gunicorn_configs_path }}"
    - "{{ pywps_configs_path }}"
    - /var/lib/pywps/outputs
    - /var/lib/pywps/outputs/{{ program_name }}
    - /var/lib/pywps/tmp
    - /var/lib/pywps/tmp/{{ program_name }}
    - /var/log/pywps
    - /var/lib/pywps/db
  tags:
    conf

- name: Copy pywps config to remote
  template:
    src: ./templates/pywps.cfg.j2
    dest: "{{ pywps_configs_path }}/{{ program_name }}.cfg"
  tags:
    conf

- name: Copy gunicorn config to remote
  template:
    src: ./templates/gunicorn.py.j2
    dest: "{{ gunicorn_configs_path }}/{{ program_name }}.py"
  tags:
    conf

- name: Copy supervisord job file to remote
  template:
    src: ./templates/supervisor.conf.j2
    dest: "{{ supervisord_configs_path }}/{{ program_name }}.conf"
    owner: root
  tags:
    conf

- name: Copy nginx config to remote
  template:
    src: ./templates/nginx.conf.j2
    dest: "{{ nginx_configs_path }}/{{ program_name }}.conf"
  tags:
    conf

- name: Copy nginx config for wps outputs to remote
  template:
    src: ./templates/nginx-wpsoutputs.conf.j2
    dest: "{{ nginx_configs_path }}/wpsoutputs.conf"
  tags:
    conf

- name: Copy start script to source folder
  template:
    src: ./templates/run.sh.j2
    dest: "{{ project_location }}/run.sh"
    owner: root
  tags:
    conf

- name: Assure application running at end of playbook
  command: /bin/true
  notify: restart pywps
  tags:
    conf
