---
# Manage the /etc/hosts file
- name: Edit /etc/hosts file
  shell: |
    grep -q "\<{{sge_server_name}}\>" /etc/hosts || echo "127.0.0.1 {{sge_server_name}}" {{sge_server_name}} >> /etc/hosts;
    grep -q "\<{{sge_submission_node}}\>" /etc/hosts || echo "127.0.0.1 {{sge_submission_node}}" {{sge_submission_node}} >> /etc/hosts;
    for i in `seq 1 {{max_number_of_nodes}}`; do
      item="{{worker_node_prefix}}${i}";
      grep -q "\<${item}\>" /etc/hosts || echo "127.0.0.1 ${item}" ${item} >> /etc/hosts;
    done

- name: create configuration directories
  file: path={{ item }} state=directory
  with_items:
    - /etc/gridengine/files/host_groups
    - /etc/gridengine/files/exec_hosts
    - /etc/gridengine/files/queues

- name: Replace bootstrap (ignore FQDN)
  copy: dest=/var/lib/gridengine/default/common/bootstrap src=bootstrap mode=0644 force=no

- name: create allhosts
  template: dest=/etc/gridengine/files/host_groups/allhosts src=allhosts

- name: start gridengine qmaster
  action: shell bash -lc '/usr/sbin/sge_qmaster'
  ignore_errors: yes

- name: add the frontend as submission host
  action: shell bash -lc 'qconf -as {{ sge_server_name }}'
  ignore_errors: yes

- name: add the submission node
  action: shell bash -lc 'qconf -as {{ sge_submission_node }}'
  ignore_errors: yes

- name: add the frontend as execution hosts
  action: shell bash -lc 'qconf -ah {{ sge_server_name }}'
  ignore_errors: yes

- name: add worker execution hosts
  action: shell bash -lc 'qconf -ah {{worker_node_prefix}}{{item}}'
  with_sequence: start=1 end={{max_number_of_nodes}}
  ignore_errors: yes

- name: Copy 'default_q.conf' file
  copy: dest=/etc/gridengine/files/queues/default.q src=default_q.conf mode=0644 force=no

- name: add hosts to the default queue
  action: shell bash -lc 'qconf -Ahgrp /etc/gridengine/files/host_groups/allhosts'
  ignore_errors: yes

- name: create default queue
  action: shell bash -lc 'qconf -Aq /etc/gridengine/files/queues/default.q'
  ignore_errors: yes

- name: kill gridengine qmaster
  action: shell bash -lc 'kill -9 `pidof sge_qmaster`'
  ignore_errors: yes
